services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - easygen-network
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - easygen-network
    depends_on:
      - backend

  # no username and password for the mongo container
  mongo:
    image: mongo:latest
    container_name: easygen-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - easygen-network

networks:
  easygen-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local 