# Use an official Node.js runtime as a parent image
FROM node:22-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to leverage Docker cache
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the application's source code
COPY . .

# The app binds to port 3000, so we'll expose that
EXPOSE 3000

# Command to run the app in development mode with hot-reloading
CMD ["npm", "run", "start:dev"] 