/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * EasyGenerator Task API
 * The EasyGenerator Task API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../utils/client';
export interface User {
  /** The user's unique email */
  email: string;
  /** The user's password */
  password: string;
  createdAt: string;
  updatedAt: string;
}

export interface SignInResponseDto {
  /** JWT access token */
  accessToken: string;
  /** JWT refresh token */
  refreshToken: string;
  /** User details */
  user: User;
}

export interface RefreshTokenResponseDto {
  /** A new JWT access token */
  accessToken: string;
}

export const appControllerHealthCheckV1 = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1`, method: 'GET', signal
    },
      );
    }
  

export const getAppControllerHealthCheckV1QueryKey = () => {
    return [`/api/v1`] as const;
    }

    
export const getAppControllerHealthCheckV1QueryOptions = <TData = Awaited<ReturnType<typeof appControllerHealthCheckV1>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheckV1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppControllerHealthCheckV1QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerHealthCheckV1>>> = ({ signal }) => appControllerHealthCheckV1(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheckV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type AppControllerHealthCheckV1QueryResult = NonNullable<Awaited<ReturnType<typeof appControllerHealthCheckV1>>>
export type AppControllerHealthCheckV1QueryError = unknown


export function useAppControllerHealthCheckV1<TData = Awaited<ReturnType<typeof appControllerHealthCheckV1>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheckV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerHealthCheckV1>>,
          TError,
          Awaited<ReturnType<typeof appControllerHealthCheckV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useAppControllerHealthCheckV1<TData = Awaited<ReturnType<typeof appControllerHealthCheckV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheckV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerHealthCheckV1>>,
          TError,
          Awaited<ReturnType<typeof appControllerHealthCheckV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useAppControllerHealthCheckV1<TData = Awaited<ReturnType<typeof appControllerHealthCheckV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheckV1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useAppControllerHealthCheckV1<TData = Awaited<ReturnType<typeof appControllerHealthCheckV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheckV1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getAppControllerHealthCheckV1QueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Refresh access token
 */
export const authControllerV1 = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<RefreshTokenResponseDto>(
      {url: `/api/v1/auth/refresh`, method: 'POST', signal
    },
      );
    }
  


export const getAuthControllerV1MutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerV1>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerV1>>, TError,void, TContext> => {

const mutationKey = ['authControllerV1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerV1>>, void> = () => {
          

          return  authControllerV1()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerV1>>>
    
    export type AuthControllerV1MutationError = void

    /**
 * @summary Refresh access token
 */
export const useAuthControllerV1 = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerV1>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerV1>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthControllerV1MutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Get current user profile
 */
export const authControllerMeV1 = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<User>(
      {url: `/api/v1/auth/me`, method: 'GET', signal
    },
      );
    }
  

export const getAuthControllerMeV1QueryKey = () => {
    return [`/api/v1/auth/me`] as const;
    }

    
export const getAuthControllerMeV1QueryOptions = <TData = Awaited<ReturnType<typeof authControllerMeV1>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMeV1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerMeV1QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerMeV1>>> = ({ signal }) => authControllerMeV1(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerMeV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type AuthControllerMeV1QueryResult = NonNullable<Awaited<ReturnType<typeof authControllerMeV1>>>
export type AuthControllerMeV1QueryError = unknown


export function useAuthControllerMeV1<TData = Awaited<ReturnType<typeof authControllerMeV1>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMeV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerMeV1>>,
          TError,
          Awaited<ReturnType<typeof authControllerMeV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useAuthControllerMeV1<TData = Awaited<ReturnType<typeof authControllerMeV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMeV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerMeV1>>,
          TError,
          Awaited<ReturnType<typeof authControllerMeV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useAuthControllerMeV1<TData = Awaited<ReturnType<typeof authControllerMeV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMeV1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get current user profile
 */

export function useAuthControllerMeV1<TData = Awaited<ReturnType<typeof authControllerMeV1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMeV1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getAuthControllerMeV1QueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
